# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08f221c615036b86d13f7585f229979d"
name = "remix-app"
handle = "remix-app-206"
application_url = "https://hydrocodone-guitars-produces-harbor.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nextjs-my-example.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hydrocodone-guitars-produces-harbor.trycloudflare.com/auth/callback",
  "https://hydrocodone-guitars-produces-harbor.trycloudflare.com/auth/shopify/callback",
  "https://hydrocodone-guitars-produces-harbor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
